# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='unique_code',
            field=models.CharField(default=None, max_length=16, unique=True),
        ),
    ]
