# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileupload_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Folder')),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Folder'),
        ),
    ]
